# Generated by Django 5.2.4 on 2025-07-22 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_avarage_rating'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'movies')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'movies')},
        ),
    ]
