# Generated by Django 5.2.4 on 2025-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avarage_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
